// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BMI.iOS
{
	public partial class ResultPopupViewController : UIViewController
	{
		public ResultPopupViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
