// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BMI.iOS
{
	public partial class SettingsViewController : UIViewController
	{
		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            tableView.Source = new SettingsTableViewSource();
            tableView.Delegate = new SettingsTableViewDelegate(this);
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
        }

        partial void TappedDone(NSObject sender)
        {
            this.DismissViewController(true, null);
        }

        partial void TappedShareWithOthers(NSObject sender)
        {
            Console.WriteLine("Share");
        } 
	}
}
